description: winprint 2.0
logo: https://tig.github.io/winprint/winprint-icon.jpg
show_downloads: true
theme: minima
minima:
  skin: sunrise
  social_links:
    twitter: ckindel
    github: tig
    stackoverflow: "ckindel"
header_pages:
  - install.md
  - users-guide.md
  - support.md
  - about.md
