description: WinPrint 2.0 - Copyright Kindel Systems, LLC
logo: https://tig.github.io/winprint/winprint-icon.jpg
show_downloads: false
theme: minima
minima:
  social_links:
    twitter: ckindel
    github: tig
    stackoverflow: ckindel
header_pages:
  - install.md
  - users-guide.md
  - support.md
  - about.md