title: winprint 2.0
description: winprint 2.0 - A modern take on the the classic source code printing app from 1988.
logo: https://tig.github.io/winprint/winprint-icon.png
theme: jekyll-theme-dinky
google_analytics: UA-4945529-9
github:
  install_url: https://github.com/tig/winprint/releases
