description: winprint 2.0
logo: https://tig.github.io/winprint/winprint-icon.jpg
theme: minima
minima:
  skin: solarized
  social_links:
    twitter: ckindel
    github: tig
    stackoverflow: "297526"
header_pages:
  - install.md
  - users-guide.md
  - support.md
  - about.md
