title: winprint 2.0
description: winprint 2.0 - A modern take on the the classic source code printing app from 1988.
logo: https://tig.github.io/winprint/winprint-icon.jpg
theme: minima
minima:
  social_links:
    twitter: ckindel
    github: tig
header_pages:
  - index.md
  - install.md
  - users-guide.md
  - support.md
  - about.md
google_analytics: UA-4945529-9

# author:
#   name: Charlie Kindel
#   email: charlie@kindel.com

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
#minima:
#  date_format: "%b %-d, %Y"

plugins:
 - jekyll-feed
 - jekyll-seo-tag
