name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        # Checkout libvt100 & litehtml
        submodules: 'true'

    # Setup .NET
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    # Restore packages
    - name: Restore
      run: dotnet restore src/WinPrint.Core

    # Build
    - name: Build
      run: dotnet build --configuration Release --no-restore src

    # Run Tests
    - name: Test
      run: dotnet test --no-restore --verbosity normal src
