name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    # Install deps
    - name: Install dependencies    
      run: |
      cd src
      dotnet restore
 
    # Build
    - name: Build
      run: |
      cd src
      dotnet build --configuration Release --no-restore
  
    # Run Tests
    - name: Test
      run: |
      cd src
      dotnet test --no-restore --verbosity normal
